apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronograf
  labels:
    app: chronograf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chronograf
  template:
    metadata:
      labels:
        app: chronograf
    spec:
      containers:
      - name: chronograf
        image: chronograf:latest
        ports:
        - containerPort: 8888
        env:
        - name: INFLUXDB_URL
          value: http://influxdb:8086
        resources:
          limits:
            memory: "256Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: chronograf
spec:
  selector:
    app: chronograf
  type: NodePort
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30888
